from contextlib import AbstractContextManager
from datetime import date, datetime
from typing import Protocol
from uuid import UUID

from a_stock_lab.features.trend_radar.domain.models import (
    Bar,
    Candidate,
    Heat,
    ListedStock,
    ScanRun,
)


class UniverseProvider(Protocol):
    def fetch_universe(self) -> list[ListedStock]: ...


class HeatProvider(Protocol):
    def fetch_heat(self) -> list[Heat]: ...


class MarketDataProvider(Protocol):
    def fetch_bars(self, symbol: str, start: date, end: date) -> list[Bar]: ...
    def close(self) -> None: ...


class TradingCalendarProvider(Protocol):
    def sessions(self, today: date) -> list[date]: ...


class LocalRepository(Protocol):
    def lock(self) -> AbstractContextManager[None]: ...
    def begin(self, run: ScanRun) -> bool: ...
    def save_run(self, run: ScanRun) -> None: ...
    def save_heat(self, run_id: UUID, heat: list[Heat]) -> None: ...
    def load_bars(self, symbol: str, vintage: date, now: datetime) -> list[Bar] | None: ...
    def save_bars(self, symbol: str, vintage: date, bars: list[Bar]) -> None: ...
    def prune_bars(self, before: date) -> None: ...
    def checkpoint(self, run: ScanRun, candidate: Candidate | None, bars: list[Bar]) -> None: ...
    def complete(
        self, run: ScanRun, results: list[Candidate], inputs: dict[str, list[Bar]]
    ) -> None: ...
    def public_runs(self) -> list[ScanRun]: ...
    def public_results(self, run_id: UUID) -> list[Candidate]: ...
    def candidate_inputs(self, run_id: UUID) -> dict[str, list[Bar]]: ...


class ResultPublisher(Protocol):
    def publish(self) -> None: ...
    def publish_progress(self) -> None: ...


class WorkerHeartbeat(Protocol):
    def write(self, now: datetime, state: str) -> None: ...
